import Hero from './Hero/Hero'
import Attributes from './Attributes/Attributes'
import About from './About/About'
import Slider from './Slider/Slider'
import Video from './Video/Video'
import Services from './Services/Services'
import Testimonials from './Testimonials/Testimonials'
import Blogs from './Blogs/Blogs'
import Footer from './Footer/Footer'
import AboutCompany from './AboutCompany/AboutCompany'
import Brands from './Brands/Brands'
import WhyUs from './WhyUs/WhyUs'
import ServicesPageHeader from './ServicesPageHeader/ServicesPageHeader'
import AboutPageHeader from './AboutPageHeader/AboutPageHeader'

export { Hero, Attributes, About, Slider, Video, Services, Testimonials, Blogs, Footer, AboutCompany, Brands, WhyUs, ServicesPageHeader, AboutPageHeader }
